# Generated by Django 4.1.7 on 2023-05-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(max_length=200, upload_to='')),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Boglanish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Boglanish',
                'verbose_name_plural': 'Boglanish',
            },
        ),
        migrations.CreateModel(
            name='Jamoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('logotip', models.ImageField(upload_to='jamoa_rasm')),
                ('jamoa_haqida', models.TextField()),
                ('rasm1', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
                ('rasm2', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
                ('rasm3', models.ImageField(blank=True, null=True, upload_to='jamoa_rasm')),
            ],
            options={
                'verbose_name': 'Jamoa',
                'verbose_name_plural': 'Jamoa',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(blank=True, max_length=300, null=True)),
                ('instagram', models.CharField(blank=True, max_length=300, null=True)),
                ('facebook', models.CharField(blank=True, max_length=300, null=True)),
                ('telegram', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Link',
            },
        ),
        migrations.CreateModel(
            name='Malumot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('malumot', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Malumot',
                'verbose_name_plural': 'Xususiyat_malumot',
            },
        ),
        migrations.CreateModel(
            name='Statistika',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('soni', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
            },
        ),
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.ImageField(upload_to='blog_rasm')),
                ('nom', models.CharField(max_length=200)),
                ('malumot', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tarif',
            },
        ),
        migrations.CreateModel(
            name='Xizmat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm1', models.ImageField(upload_to='blog_rasm')),
                ('rasm2', models.ImageField(upload_to='blog_rasm')),
                ('rasm3', models.ImageField(upload_to='blog_rasm')),
            ],
            options={
                'verbose_name': 'Xizmat',
                'verbose_name_plural': 'Xizmatlar',
            },
        ),
        migrations.CreateModel(
            name='Xususiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('rasm', models.ImageField(upload_to='blog_rasm')),
            ],
            options={
                'verbose_name': 'Xususiyat',
                'verbose_name_plural': 'Xususiyat',
            },
        ),
    ]
