# Generated by Django 4.0.6 on 2023-05-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
