# Generated by Django 4.0.6 on 2023-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_blog_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='kurishlar',
            field=models.IntegerField(default=0),
        ),
    ]
